### ISSUE TITLE
'sanity' is not recognized as an internal or external command in /build/studio

### ISSUE THREAD

**Issue by jSwtch** [sanity-io/sanity-template-sapper-blog#2]
Install dependencies with npm install in the root folder. [OK]
Run npm run dev in root folder. [OK]
Run npm install in ./build/web. [OK]
Run sanity install in /build/studio 
'sanity' is not recognized as an internal or external command,
Run npm run dev in ./build/web. [OK]
Run and sanity start in /build/studio.
...
Win10 nodev10.1.x & nodev12.3.1

**Comment by kmelve** [comment]
Thanks for the report! We're looking into this, stay tuned.

**Comment by thompcd** [comment]
Same issue here. MacOS 10.13.6, node 8.15.1

**Comment by kmelve** [comment]
I believe this is resolved now?

**Comment by alexPalita** [comment]
> Install dependencies with npm install in the root folder. [OK]
> Run npm run dev in root folder. [OK]
> Run npm install in ./build/web. [OK]
> Run sanity install in /build/studio
> 'sanity' is not recognized as an internal or external command,
> Run npm run dev in ./build/web. [OK]
> Run and sanity start in /build/studio.
> ...
> Win10 nodev10.1.x & nodev12.3.1

Hello i have the same issue here :( . 
Win 10 node -v12.16.1

**Comment by postdigitalist** [comment]
Hi, I'm having the same issue. I'm on Win 10 and my version of Node is 13.13.0.

**Comment by Gcarter17** [comment]
Just had this same problem when trying to install a plugin for the first time, in the root package.json file I updated "@sanity/cli" to "1.149.13" as such  
`"@sanity/cli": "1.149.13",`
ran npm install, then everything was working how it was supposed to

**Comment by shahidAhmadDev** [comment]
hello when i try to install sanity  from this command on windows 11 ...npm install -g @sanity/cli && sanity init .I am getting this error  'sanity' is not recognized as an internal or external command, operable program or batch file.

**Comment by AmanBhanse** [comment]
The same issue, I am cloning one project into my laptop ([link](https://github.com/AmanBhanse/personal-portfolio)).
sanity is present inside the backend folder, you need to `cd backend` and when I tried to run `sanity start`, it throws an error (one mentioned above).

Can someone please check on this?

Win11 , node 16.14.2 , npm 8.11.0

**Comment by Maijied** [comment]
Same problem in windows 10 , Node: v16.13.1

sanity : The term 'sanity' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again

**Comment by 0xSimbaDev** [comment]
I also having the same issue. Windows 11, Node v.16.16.0 

'sanity' is not recognized as an internal or external command,
operable program or batch file.

**Comment by masonintokyo** [comment]
I run into same issue after bought a new computer. ( windows 11 )
The issue was caused by windows' execution policy for my case.
Change your execution policy to accept RemoteSigned stuffs by running `Set-ExecutionPolicy RemoteSigned` in PowerShell as admin. You can check current execution policy with `Get-ExecutionPolicy`.
And the problem is gone.

**Comment by 0xSimbaDev** [comment]
@szriru Thanks mate, I will try this.

**Comment by 0xSimbaCrypto** [comment]
@szriru it seems that I'm still having the same error "sanity is not recognized as an internal or external command"

**Comment by 0xSimbaDev** [comment]
It seems that I am still having the same error "sanity' is not recognized as an internal or external command" @szriru 

> I run into same issue after bought a new computer. ( windows 11 ) The issue was caused by windows' execution policy for my case. Change your execution policy to accept RemoteSigned stuffs by running `Set-ExecutionPolicy RemoteSigned` in PowerShell as admin. You can check current execution policy with `Get-ExecutionPolicy`. And the problem is gone.

**Comment by 0xSimbaDev** [comment]
I found this solution on https://stackoverflow.com/questions/67031964/error-when-i-try-to-execute-sanity-start-after-success-with-sanity-init. 

I use this command instead npx @sanity/cli init

**Comment by masonintokyo** [comment]
@0xSimbaCrypto
yes you should `npm install -g @sanity/cli`
Glad to hear you solved the problem.
