### ISSUE TITLE
Cache content when exporting

### ISSUE THREAD

**Issue by antony** [sanity-io/sanity-template-sapper-blog#42]
I've noticed that `sapper export` exports static pages, but only caches content if it is requested from the same domain. So this template doesn't produce a truly static site (it still does lots of API requests).

The solution to this is the proxy the content fetch via server-routes (i.e. /api/[slug].js) as the original Sapper template does. This way all the API requests are cached and the site is finally static.

I'd be happy to attempt a PR for this, if it's something you would want to incorporate.

**Comment by kmelve** [comment]
Hi! I believe there was some bug or issues when I originally set this up that prevented us for making it fully static. A PR is more than welcome if you want to take a stab at it. Thanks!

**Comment by eur2** [comment]
Hi @kmelve , these API requests and the "not truly static site" issue are making this template slow and not so ready for production. Do you think you could merge the PR from @antony ?
