### ISSUE TITLE
All blog links missing trailing "/", causing 500 error

### ISSUE THREAD

**Issue by franknoirot** [sanity-io/sanity-template-sapper-blog#9]
I'm still learning web development, apologies if this is uninformed!

In the standard installation, all links in /blog subdirectory (including Blog link in global nav) do not work without a trailing "/". When one is added everything loads fine.

For example, /blog produces the following error:
```500 Network error while attempting to reach https://67v1lkui.apicdn.sanity.io/v1/data/query/production?query=*%5B_type%20%3D%3D%20%22post%22%20%26%26%20defined(slug.current)%20%26%26%20publishedAt%20%3C%20now()%5D%7Corder(publishedAt%20desc)```

https://neta-sapper-sanity.netlify.com/blog
vs.
https://neta-sapper-sanity.netlify.com/blog/

I'd love to learn how to set up RegEx redirects with this stack! Unsure if that would be handled by Sapper or Sanity.

**Comment by franknoirot** [comment]
Apologies I was incorrect!

**Comment by evenwestvang** [comment]
No problem @franknoirot!

**Comment by bugbit-io** [comment]
Hi @franknoirot, I'm also having this - what is the real issue?
